name: "Send new Tweets from @maja_fuckn_cat to Telegram Channel"

env:
  SCREEN_NAME: maja_fuckn_cat

on:
  twitter:
    api: statuses/user_timeline
    auth:
      consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
      consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      access_token_secret: ${{ secrets.TWITTER_ACCESS_SECRET }}
    params:
      screen_name: ${{ env.SCREEN_NAME }}
      include_rts: false

jobs:
  telegram:
    name: "Send Tweet to Telegram Channel"
    runs-on: ubuntu-latest
    steps:
      - name: "Send Telegram Message"
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TWITTER_TELEGRAM_CHATID }}
          token: ${{ secrets.TWITTER_TELEGRAM_TOKEN }}
          format: html
          message: |
            <a href="https://twitter.com/${{ env.SCREEN_NAME }}/status/${{ on.twitter.outputs.id_str }}">New Tweet by @${{ env.SCREEN_NAME }}</a>