name: "Share new Tweets from me and my friends on a Telegram channel"

on:
  twitter:
    api: search/tweets
    auth:
      consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
      consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    params:
      q: "list:${{ secrets.TWITTER_LIST_ID }} -filter:replies -filter:retweets"
      result_type: recent
      include_entities: false
    config:
      sortScript: |
        return new Date(a.created_at) - new Date(b.created_at)

jobs:
  telegram:
    name: "Send Tweet to Telegram Channel"
    runs-on: ubuntu-latest
    steps:
      - name: "Send Telegram Message"
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TWITTER_TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TWITTER_TELEGRAM_TOKEN }}
          format: html
          message: |
            <a href="https://twitter.com/${{ on.twitter.outputs.user.screen_name }}/status/${{ on.twitter.outputs.id_str }}">New Tweet by @${{ on.twitter.outputs.user.screen_name }}</a>
