name: "Share new Instagram posts on Twitter"

on:
  instagram:
    access_token: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}

jobs:
  tweet:
    name: "Tweet new Instagram posts"
    runs-on: ubuntu-latest
    steps:
      - name: "Tweet permalink"
        uses: ethomson/send-tweet-action@v1
        with:
          status: ${{ on.instagram.outputs.permalink }}
          consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}