name: "Send new Tweets from @Skayo_ to Telegram Channel"

on:
  twitter:
    api: statuses/user_timeline
    auth:
      consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
      consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      access_token_secret: ${{ secrets.TWITTER_ACCESS_SECRET }}
    params:
      screen_name: Skayo_

jobs:
  telegram:
    name: "Send Tweet to Telegram Channel"
    runs-on: ubuntu-latest
    steps:
      - name: "Send Telegram Message"
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: "[New Tweet by @${{ on.twitter.outputs.user.screen_name }}](https://twitter.com/${{ on.twitter.outputs.user.screen_name }}/${{ on.twitter.outputs.id }})"